<?php
/**
 * Explore Prompts Gallery
 */
require_once __DIR__ . '/auth.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Explore — Grok Imagine Playground</title>
    <meta name="description" content="Explore thousands of high-quality AI prompts and outputs generated by Grok Imagine.">
    <link rel="icon" type="image/svg+xml" href="favicon.svg">
    <link rel="stylesheet" href="css/style.css">
    <style>
        .explore-header {
            text-align: center;
            padding: 60px 0 40px;
        }
        .filter-bar {
            background: var(--bg-card);
            border: 1px solid var(--border);
            padding: 16px;
            border-radius: var(--radius-lg);
            margin-bottom: 30px;
            display: flex;
            gap: 12px;
            flex-wrap: wrap;
            align-items: center;
            backdrop-filter: blur(10px);
        }
        .search-input {
            flex: 1;
            min-width: 200px;
            background: rgba(255, 255, 255, 0.05);
            border: 1px solid var(--border);
            padding: 10px 16px;
            border-radius: var(--radius-md);
            color: #fff;
            outline: none;
        }
        .search-input:focus { border-color: var(--accent-1); }
        
        .gallery-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            gap: 24px;
            margin-bottom: 50px;
        }
        .gallery-card {
            background: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: var(--radius-lg);
            overflow: hidden;
            transition: all 0.3s ease;
            cursor: pointer;
            display: flex;
            flex-direction: column;
        }
        .gallery-card:hover {
            transform: translateY(-5px);
            border-color: rgba(99, 102, 241, 0.3);
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.4);
        }
        .card-media {
            width: 100%;
            height: 200px;
            background: #000;
            position: relative;
            overflow: hidden;
        }
        .card-media img, .card-media video {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        .card-type {
            position: absolute;
            top: 12px;
            right: 12px;
            padding: 4px 10px;
            background: rgba(0, 0, 0, 0.6);
            backdrop-filter: blur(4px);
            border-radius: 6px;
            font-size: 10px;
            font-weight: 600;
            text-transform: uppercase;
            color: var(--accent-3);
        }
        .card-info {
            padding: 16px;
            flex: 1;
            display: flex;
            flex-direction: column;
            gap: 8px;
        }
        .card-title {
            font-size: 16px;
            font-weight: 600;
            color: #fff;
        }
        .card-prompt {
            font-size: 13px;
            color: var(--text-secondary);
            display: -webkit-box;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
            overflow: hidden;
        }
        .card-footer {
            padding: 12px 16px;
            border-top: 1px solid var(--border);
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .vote-tools {
            display: flex;
            align-items: center;
            gap: 8px;
        }
        .vote-btn {
            background: none;
            border: none;
            color: var(--text-muted);
            cursor: pointer;
            padding: 4px;
            display: flex;
            align-items: center;
            transition: color 0.2s;
        }
        .vote-btn:hover { color: var(--text-primary); }
        .vote-btn.active.up { color: var(--success); }
        .vote-btn.active.down { color: var(--error); }
        .vote-count { font-size: 13px; font-weight: 600; min-width: 20px; text-align: center; }

        .gen-textarea, .gen-balance {
            white-space: pre-wrap;
            word-break: break-word;
            line-height: 1.6;
        }
        .modal {
            position: fixed;
            inset: 0;
            z-index: 1000;
            background: rgba(0, 0, 0, 0.8);
            backdrop-filter: blur(12px);
            display: none;
            align-items: center;
            justify-content: center;
            padding: 20px;
            max-width: 100%;
        }
        .modal-content {
            background: #0a0a0b;
            border: 1px solid var(--border);
            border-radius: var(--radius-xl);
            max-width: 960px;
            width: 100%;
            height: auto;
            max-height: 90vh;
            overflow: hidden;
            position: relative;
            display: flex;
            box-shadow: 0 40px 100px rgba(0,0,0,0.8);
        }
        .modal-media { 
            flex: 1.4; 
            background: #000;
            display: flex;
            align-items: center;
            justify-content: center;
            border-right: 1px solid var(--border);
            min-height: 400px;
        }
        .modal-media img, .modal-media video { 
            max-width: 100%; max-height: 90vh; object-fit: contain; 
        }
        .modal-details { 
            flex: 1; 
            padding: 32px;
            display: flex; 
            flex-direction: column; 
            gap: 16px;
            overflow-y: auto;
        }
        .modal-close {
            position: absolute; top: 16px; right: 16px; cursor: pointer; color: var(--text-muted); z-index: 10;
            background: rgba(0,0,0,0.5); border-radius: 50%; padding: 4px; display: flex;
        }
        @media (max-width: 900px) {
            .modal-content { flex-direction: column; max-height: 95vh; overflow-y: auto; }
            .modal-media { border-right: none; border-bottom: 1px solid var(--border); min-height: 300px; flex: none; }
            .modal-details { padding: 20px; flex: none; }
        }
    </style>
</head>
<body>
    <div class="bg-glow"></div>
    <div class="bg-glow-2"></div>
    <div class="bg-grid"></div>

    <header class="header">
        <div class="header-inner">
            <a href="/" class="logo">
                <img src="images/logo.svg" alt="Logo" class="logo-icon" width="28" height="28">
                <span>Grok Playground</span>
            </a>
            <div class="header-nav">
                <a href="/" class="btn btn-ghost btn-sm">Home</a>
                <div id="userProfile" style="display:none;">
                    <div class="user-avatar" onclick="window.location.href='/admin.html'">
                        <img id="userPicture" src="" alt="">
                    </div>
                </div>
            </div>
        </div>
    </header>

    <main class="main" style="max-width: 1200px;">
        <div class="explore-header">
            <h1 class="hero-title"><span class="gradient-text">Explore</span> Masterpieces</h1>
            <p class="hero-sub">Discover, learn, and remix prompts from the community.</p>
        </div>

        <div class="filter-bar">
            <input type="text" id="searchInput" class="search-input" placeholder="Search prompts or keywords...">
            <select id="categoryFilter" class="option-select" style="width: auto;">
                <option value="">All Categories</option>
                <!-- Categories loaded via JS -->
            </select>
            <select id="typeFilter" class="option-select" style="width: auto;">
                <option value="">All Modalities</option>
                <option value="text_to_image">Images</option>
                <option value="image_to_video">Videos</option>
                <option value="text_to_audio">Audio</option>
            </select>
            <select id="sortOrder" class="option-select" style="width: auto;">
                <option value="newest">Newest First</option>
                <option value="top">Top Rated</option>
            </select>
            <button class="btn btn-primary btn-sm" onclick="loadGallery(1)">Search</button>
        </div>

        <div class="gallery-grid" id="galleryGrid">
            <!-- Items loaded via JS -->
            <div class="loading-area" style="grid-column: 1/-1;">
                <div class="loading-spinner"></div>
                <p>Curating gallery...</p>
            </div>
        </div>

        <div class="history-pagination" id="pagination"></div>
    </main>

    <!-- Detail Modal -->
    <div class="modal" id="detailModal">
        <div class="modal-content">
            <div class="modal-close" onclick="closeModal()">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 6L6 18M6 6l12 12"/></svg>
            </div>
            <div class="modal-media" id="modalMedia"></div>
            <div class="modal-details">
                <div id="modalType" class="history-item-type">IMAGE</div>
                <h2 id="modalTitle" class="install-title" style="margin:0;">Title</h2>
                <div class="section">
                    <label class="gen-label">Prompt</label>
                    <div id="modalPrompt" class="gen-textarea" style="background:rgba(255,255,255,0.05); min-height:80px; padding:12px; border-radius:8px;"></div>
                </div>
                <div class="section" id="descriptionSection" style="display:none;">
                    <label class="gen-label">Description</label>
                    <div id="modalDescription" class="gen-textarea" style="background:rgba(255,255,255,0.03); min-height:40px; padding:12px; border-radius:8px; font-size:13px; color:var(--text-secondary);"></div>
                </div>
                <div class="section" id="settingsInfo">
                    <label class="gen-label">Technical Details</label>
                    <div id="modalSettings" class="gen-balance" style="font-size:12px; line-height:1.6;"></div>
                </div>
                <div class="install-actions">
                    <button class="btn btn-primary" onclick="copyPrompt()">Copy Prompt</button>
                    <button class="btn btn-ghost" onclick="downloadModalOutput()">Download</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://www.gstatic.com/firebasejs/9.22.1/firebase-app-compat.js"></script>
    <script src="https://www.gstatic.com/firebasejs/9.22.1/firebase-auth-compat.js"></script>
    <script src="js/firebase-config.js"></script>
    <script>
        let currentUser = null;
        let authReady = false;

        firebase.auth().onAuthStateChanged(user => {
            currentUser = user;
            authReady = true;
            if (user) {
                document.getElementById('userProfile').style.display = 'flex';
                document.getElementById('userPicture').src = user.photoURL || 'images/avatar.png';
            }
            loadCategories();
            loadGallery(1);
        });

        async function loadCategories() {
            const res = await fetch('api/categories.php');
            const data = await res.json();
            if (data.success) {
                const select = document.getElementById('categoryFilter');
                data.categories.forEach(cat => {
                    const opt = document.createElement('option');
                    opt.value = cat.id;
                    opt.textContent = cat.name;
                    select.appendChild(opt);
                });
            }
        }

        async function loadGallery(page = 1) {
            const type = document.getElementById('typeFilter').value;
            const categoryId = document.getElementById('categoryFilter').value;
            const q = document.getElementById('searchInput').value;
            const sort = document.getElementById('sortOrder').value;
            
            const grid = document.getElementById('galleryGrid');
            const res = await fetch(`api/showcase.php?page=${page}&type=${type}&category_id=${categoryId}&q=${encodeURIComponent(q)}&sort=${sort}`);
            const data = await res.json();
            
            if (data.success) {
                renderGrid(data.items);
                renderPagination(data.pagination);
            }
        }

        function renderGrid(items) {
            const grid = document.getElementById('galleryGrid');
            if (items.length === 0) {
                grid.innerHTML = '<div style="grid-column:1/-1; text-align:center; padding:50px; color:var(--text-muted);">No gems found. Try a different search.</div>';
                return;
            }

            grid.innerHTML = items.map(item => `
                <div class="gallery-card" onclick="showDetails(${JSON.stringify(item).replace(/"/g, '&quot;')})">
                    <div class="card-media">
                        ${renderMedia(item)}
                        <span class="card-type">${item.type.replace(/_/g, ' ')}</span>
                    </div>
                    <div class="card-info">
                        <h3 class="card-title">${item.title}</h3>
                        ${item.category_name ? `<span style="font-size:10px; color:var(--accent-2); margin-top:-4px; text-transform:uppercase; font-weight:700;">${item.category_name}</span>` : ''}
                        <p class="card-prompt">${item.prompt}</p>
                    </div>
                    <div class="card-footer" onclick="event.stopPropagation()">
                        <div class="vote-tools">
                            <button class="vote-btn up" onclick="handleVote(${item.id}, 1)">
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 19V5M5 12l7-7 7 7"/></svg>
                            </button>
                            <span class="vote-count" id="votes-${item.id}">${item.votes}</span>
                            <button class="vote-btn down" onclick="handleVote(${item.id}, -1)">
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12l7 7 7-7"/></svg>
                            </button>
                        </div>
                        <div class="gen-cost"><strong>${item.model_used}</strong></div>
                    </div>
                </div>
            `).join('');
        }

        function renderMedia(item) {
            if (item.type === 'text_to_image') return `<img src="${item.output_url}" loading="lazy">`;
            if (item.type === 'text_to_audio') return `<div class="history-item-placeholder"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></svg></div>`;
            return `<video src="${item.output_url}" loading="lazy" muted onmouseover="this.play()" onmouseout="this.pause();this.currentTime=0;"></video>`;
        }

        async function handleVote(itemId, direction) {
            if (!currentUser) {
                alert("Please log in to vote!");
                return;
            }
            const idToken = await currentUser.getIdToken();
            const res = await fetch('api/showcase.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + idToken },
                body: JSON.stringify({ item_id: itemId, vote: direction })
            });
            const data = await res.json();
            if (data.success) {
                document.getElementById(`votes-${itemId}`).textContent = data.new_votes;
            }
        }

        function showDetails(item) {
            const modal = document.getElementById('detailModal');
            document.getElementById('modalTitle').textContent = item.title;
            document.getElementById('modalPrompt').textContent = item.prompt;
            document.getElementById('modalType').textContent = item.type.toUpperCase().replace(/_/g, ' ');
            
            const descSec = document.getElementById('descriptionSection');
            if (item.description && item.description.trim() !== '') {
                document.getElementById('modalDescription').textContent = item.description;
                descSec.style.display = 'block';
            } else {
                descSec.style.display = 'none';
            }
            let mediaHtml = '';
            if (item.type === 'text_to_image') mediaHtml = `<img src="${item.output_url}">`;
            else if (item.type === 'text_to_audio') mediaHtml = `<audio src="${item.output_url}" controls autoplay></audio>`;
            else mediaHtml = `<video src="${item.output_url}" controls autoplay loop></video>`;
            
            document.getElementById('modalMedia').innerHTML = mediaHtml;
            
            const settings = JSON.parse(item.settings_json || '{}');
            document.getElementById('modalSettings').innerHTML = `
                Model: <strong>${item.model_used}</strong><br>
                ${Object.entries(settings).map(([k,v]) => `${k}: <strong>${v}</strong>`).join('<br>')}
            `;
            
            modal.style.display = 'flex';
            modal.dataset.currentPrompt = item.prompt;
            modal.dataset.currentUrl = item.output_url;
        }

        function closeModal() {
            document.getElementById('detailModal').style.display = 'none';
            document.getElementById('modalMedia').innerHTML = '';
        }

        function copyPrompt() {
            const prompt = document.getElementById('detailModal').dataset.currentPrompt;
            navigator.clipboard.writeText(prompt);
            alert("Prompt copied!");
        }

        function downloadModalOutput() {
            const url = document.getElementById('detailModal').dataset.currentUrl;
            window.open(url, '_blank');
        }

        function renderPagination(p) {
            const nav = document.getElementById('pagination');
            if (p.total_pages <= 1) {
                nav.innerHTML = '';
                return;
            }
            let html = `<button class="page-btn" ${p.current_page === 1 ? 'disabled' : ''} onclick="loadGallery(${p.current_page - 1})">Prev</button>`;
            html += `<span class="page-info">Page ${p.current_page} of ${p.total_pages}</span>`;
            html += `<button class="page-btn" ${p.current_page === p.total_pages ? 'disabled' : ''} onclick="loadGallery(${p.current_page + 1})">Next</button>`;
            nav.innerHTML = html;
        }

        window.onclick = function(event) {
            const modal = document.getElementById('detailModal');
            if (event.target == modal) closeModal();
        }
    </script>
</body>
</html>
